### ISSUE TITLE
Question about pre-computed

### ISSUE THREAD

**Issue by Sample-design-alt** [locuslab/trellisnet#7]
Hello,

I was reading your paper and having a question about
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L55,I don't think it can reduce the computation,How did it work? Is it true that I can only find one cycle and only reduce one calculation that  in the layer 1?

**Comment by shaojieb** [comment]
Hi @Sample-design-alt ,

Thanks for your question! That line is not to reduce the computation, but to make the code compatible with the pytorch version at the time. Without the device id as part of the key, the old pytorch would produce inconsistent device id error, so this line is there just to ensure the `self.weight1` and `x1` are on the same device.

As you can see on https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L59 and https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L147, this pre-computed input injection is re-used for each layer in a training iteration; then when a new iteration begins, the caching is cleared.

Hope this helps! :-)

**Comment by Sample-design-alt** [comment]
Thanks for your prompt reply.

Q1:So the function of the dictionary is to ensure the pytorch version work well?But why self.weight2 don't need the dictionary?https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L59

Q2:But I think the issue is not clear for me.what is pre-computed?
        As your paper said "we can precompute the linear transformation x\~t+1=Wx1*xt+Wx2*Xt+1 for all layers i" . My opinion about that  x~t+1 is equal to Input injection,and then has computated before trellisnet run, when trellisnet start ,Just take it out and add convolution(the left part of formula 11).There is not additional computation in Input injection.

**Comment by shaojieb** [comment]
A1: The dictionary is not for weight1, it's for the result of applying weight1 on the input sequence. This result, which is the input injection \tilde{x}, is fixed, so we can compute it once and store it. But the weight2 is applied on `z_1`, which keeps changing for each layer. We certainly don't/can't/shouldn't use a dictionary for it.

A2: In each iteration, the input injection is pre-computed. There are two ways to add \tilde{x} to the convolution: 1) re-compute "\tilde{x}=Wx... " at every layer of the network, which is a waste of resource because we are doing redundant, repetitive computations many times; or 2) **pre-compute** it only once, and then add the result to every layer (i.e., "injection"). We adopted (2), and call it the input injection.

**Comment by Sample-design-alt** [comment]
However, after adding the dictionary https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L56,
 the dictionary is called only once
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L59, 
and it is cleared after an iteration. I still don't understand precomputation. I think it is OK to adapt the code as follows. Is this also called precomputation?
![image](https://user-images.githubusercontent.com/66257621/99612189-10a60c80-2a50-11eb-8cb8-707aa8da2e88.png)

**Comment by shaojieb** [comment]
Yes, you can write in this way, but this is NOT precomputation. If you write it in this way, then every layer of the TrellisNet will have to compute `F.conv1d(x_1, self.weight1, dilation=dilation)` once, right? So if you have a 50-layer TrellisNet, you will compute this 50 times. But the fact is, you don't need to compute it every time, as it's a fixed quantity: `x_1` is fixed for a training iteration, `self.weight1` is fixed for a training iteration, etc.).

This dictionary is not just called once. It's called `self.nlevels` times (e.g., 50), once in each `self.step` call:
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L155
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L118

So you can compute it "before you enter the layers" (thus the prefix "pre-" in "pre-compute"; i.e., *预先*计算). Instead of RE-computing this convolution, we **PRE-compute** it. 

Does this clarify my point?

**Comment by Sample-design-alt** [comment]
But dilation is different in every levels,the value of the dictionary will be different.which is passed to
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L55-L56
The division will be different I think precomputation can only be done when the divisions are the same. As you said, after each iteration, the cache will be empty (because the weight 1 has changed). I saw that you pointed out in your first paper on TCN that the exponential growth of 2 will make the division of each layer different 
Maybe I can't explain it well in English. I want to explain it in Chinese once again.
但是每一层的dilation都是不同的，再传递给
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L55-L56
的dilation也会不同 我觉得预计算是只有当dilation都相同的时候才可以进行预计算，并且正如您所说，当每一次的迭代完成之后，cache就会清空（因为weigh1发生了变化），dilation我看到您在第一篇关于TCN的论文中指出了，是2的指数级增长，那每一层的dilation就会不相同（只有第一层和第二层的dilation相同，dilation都是为1）

**Comment by shaojieb** [comment]
Yes, if the dilation sizes are different then indeed the dictionaries will be written and read only once (and are thus useless). But in the TrellisNet implementation, they are in a cycle:
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/trellisnet.py#L154
In other words, the dilation sizes of the layers could be something like `[1,2,4,8,1,2,4,8,...]`. Then in this case precomputation will make a difference. Moreover, in tasks like WT103, we really are just using a dilation cycle `[1]`, which means *all layers have dilation size 1*:
https://github.com/locuslab/trellisnet/blob/ec1de0a5ee09ef5a4c5bca4c83456dec8cbdf4c8/TrellisNet/word_WT103/word_wt103.py#L83

The key point is, the dilation sizes don't have to go exponentially the way the canonical TCN did. Even WaveNet did this cyclic dilation broadening.

And this is really just an implementation issue (whether to use a dictionary or not) to speed things up.

**Comment by Sample-design-alt** [comment]
Thanks for your reply!  
I have got it. I always thought that dilation had to grow exponentially and I didn't notice that it could be a cycle Because I only saw seq_mnist_cifar which dilation was grow exponentially.
The issue can be close,thanks for your generous answer once again 👍
